# Site Settings
title: Website Test Project
description: My first steps in creating Jekyll websites on GitHub 

# My SEO
google_analytics: UA-61449151-2

# My Functionality
show_downloads: false

# Build Settings
markdown: kramdown
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions

# exclude:
# - README.md
# - gh-pages.md
 
# Add projects to the collections
collections:
  projects:
    output: true

# Layout Settings
defaults:
 -
   scope:
     path: "projects"
     type: "pages" # We can create our own collection, if we like.
   values:
     layout: "project"
     author: "Marco M. von Hagen"
     codename: "m2vh"
