title: Website Test Project
description: My first steps in creating Jekyll websites on GitHub 
google_analytics: UA-61449151-2
show_downloads: false
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
